### ISSUE TITLE
The solution of `data packing` in the summary video fail to pass the CI.

### ISSUE THREAD

**Issue by fuyw** [dendibakh/perf-ninja#46]
Hello Denis, 

Following solution in the summary video failed to pass the CI for the `data packing` lab.

```cpp
struct S {
  float d;
  long long l:16;
  int i:8;
  short s:7;
  bool b:1;

  bool operator<(const S &s) const { return this->i < s.i; }
};
```

In particular, `short s:7;` failed to pass the validation.

```
Scanning dependencies of target validateLab
Validation Failed. Value s is -28. Expected is 100 for intialization values 0 and 100
Validation Failed. Value s is -29. Expected is 99 for intialization values 1 and 99
Validation Failed. Value s is -28. Expected is 100 for intialization values 100 and 100
make[3]: *** [CMakeFiles/validateLab.dir/build.make:57: CMakeFiles/validateLab] Error 2
make[2]: *** [CMakeFiles/Makefile2:134: CMakeFiles/validateLab.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/validateLab.dir/rule] Error 2
make: *** [Makefile:144: validateLab] Error 2
Will benchmark the lab: memory_bound:data_packing
Build and Validate the solution
Prepare build directory - OK
CMake - OK
Build - OK
Validation - Failed
```

If we just set `short s;`, then the new version would be slower:
```
Benchmark                   Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------
bench1                   +0.0307         -0.0028           419           432           420           419
New version is slower. Submission for the lab memory_bound:data_packing failed.
```

**Comment by dendibakh** [comment]
Please keep in mind that bitfields should be unsigned. Which compiler you're using?

**Comment by fuyw** [comment]
Hello Denis, many thanks for the reminder.

Above logs are copied from the CI outputs with Clang 12.0.0.

I tried to add `unsigned`, but it is still not fast enough to pass the CI.

**Comment by dendibakh** [comment]
> 

Ah, so it validates, but is not fast enough, correct? I thought that the problem is with validation.

Yeah, indeed, I checked your branch and the solution looks good. I guess I need to check it...
There could be other effects that come into play. I tried to mitigate code alignment issues with https://github.com/dendibakh/perf-ninja/commit/6a8b9ed1f5065942a513073ed2cd54ec8da33a63.

**Comment by fuyw** [comment]
Thanks Denis. Thanks again for this awesome course.

**Comment by dendibakh** [comment]
BTW, it passed on Linux with a 23% speedup. But not on Windows. @stdbug , could it be an issue with the AMD runner? I believe I tested the same solution a few months ago and everything was fine (I saw at least 10% speedup).

I think this must be some weird HW effect that comes into play and tanks the performance of your code @fuyw . Sorry about that.

**Comment by stdbug** [comment]
It seems to be more Windows issue rather than AMD. I checked solutions using WSL Debian 11 on the very same machine and it gives expected results

As for Windows, first of all, the results on WinAMD runner are not as stable as I'd like them to be. I tried running both @fuyw's and my own earlier solutions with different struct layouts, but benchmark results are swinging by a number of percents

The second thing is more interesting. @fuyw's struct with different data types for fields (`long long`, `int`, `short`, `bool`) results in a bigger struct size than you'd expect. My guess is that it's because on Windows Clang [attempts to be compatible](https://clang.llvm.org/docs/MSVCCompatibility.html#:~:text=Clang%20is%20compatible%20with%20Microsoft's,Microsoft's%20extension%20is%20non-conforming.) with Microsoft Visual C++ which [doesn't merge](https://randomascii.wordpress.com/2010/06/06/bit-field-packing-with-visual-c/) fields of different base sizes. Both links are quite sparse on details, but that's all I could find by quick googling
